# Name                    Version                   Build  Channel
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0                   pypi_0    pypi
blas                      1.0                         mkl  
bottleneck                1.3.5           py311hb9e55a9_0  
bzip2                     1.0.8                h1de35cc_0  
ca-certificates           2023.11.17           h8857fd0_0    conda-forge
comm                      0.1.4              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.0                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
debugpy                   1.6.7           py311h814d153_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.0              pyhd8ed1ab_0    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
fastjsonschema            2.19.0                   pypi_0    pypi
fonttools                 4.46.0                   pypi_0    pypi
greenlet                  3.0.1                    pypi_0    pypi
importlib-metadata        7.0.0              pyha770c72_0    conda-forge
importlib_metadata        7.0.0                hd8ed1ab_0    conda-forge
install                   1.3.5                    pypi_0    pypi
intel-openmp              2023.1.0         ha357a0b_43548  
ipykernel                 6.26.0             pyh3cd1d5f_0    conda-forge
ipython                   8.18.1             pyh707e725_3    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
joblib                    1.3.2                    pypi_0    pypi
jsonschema                4.20.0                   pypi_0    pypi
jsonschema-specifications 2023.11.2                pypi_0    pypi
jupyter_client            8.6.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.5.0           py311h6eed73b_0    conda-forge
kiwisolver                1.4.5                    pypi_0    pypi
libcxx                    14.0.6               h9765a3e_0  
libffi                    3.4.4                hecd8cb5_0  
libsodium                 1.0.18               hbcb3906_1    conda-forge
matplotlib                3.8.2                    pypi_0    pypi
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
missingno                 0.5.2                    pypi_0    pypi
mkl                       2023.1.0         h8e150cf_43560  
mkl-service               2.4.0           py311h6c40b1e_1  
mkl_fft                   1.3.8           py311h6c40b1e_0  
mkl_random                1.2.4           py311ha357a0b_0  
nbformat                  5.9.2                    pypi_0    pypi
ncurses                   6.4                  hcec6c5f_0  
nest-asyncio              1.5.8              pyhd8ed1ab_0    conda-forge
numexpr                   2.8.7           py311h728a8a3_0  
numpy                     1.26.2          py311h728a8a3_0  
numpy-base                1.26.2          py311h53bf9ac_0  
openssl                   3.2.0                hd75f5a5_1    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    2.1.3                    pypi_0    pypi
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
patsy                     0.5.4                    pypi_0    pypi
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.1.0                   pypi_0    pypi
pip                       23.3.1          py311hecd8cb5_0  
platformdirs              4.1.0              pyhd8ed1ab_0    conda-forge
plotly                    5.18.0                   pypi_0    pypi
prompt-toolkit            3.0.42             pyha770c72_0    conda-forge
psutil                    5.9.5           py311h2725bcf_1    conda-forge
psycopg2                  2.9.9                    pypi_0    pypi
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pyaml                     23.9.7                   pypi_0    pypi
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.1                    pypi_0    pypi
pyscopg2                  66.0.2                   pypi_0    pypi
python                    3.11.5               hf27a42d_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-tzdata             2023.3             pyhd3eb1b0_0  
python_abi                3.11                    2_cp311    conda-forge
pytz                      2023.3.post1    py311hecd8cb5_0  
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     25.0.2          py311habfacb3_0    conda-forge
readline                  8.2                  hca72f7f_0  
referencing               0.32.0                   pypi_0    pypi
rpds-py                   0.15.2                   pypi_0    pypi
scikit-learn              1.3.2                    pypi_0    pypi
scipy                     1.11.4                   pypi_0    pypi
seaborn                   0.13.0                   pypi_0    pypi
setuptools                68.0.0          py311hecd8cb5_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlalchemy                2.0.23                   pypi_0    pypi
sqlite                    3.41.2               h6c40b1e_0  
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
statsmodels               0.14.1                   pypi_0    pypi
tbb                       2021.8.0             ha357a0b_0  
tenacity                  8.2.3                    pypi_0    pypi
threadpoolctl             3.2.0                    pypi_0    pypi
tk                        8.6.12               h5d9f67b_0  
tornado                   6.3.3           py311h2725bcf_1    conda-forge
traitlets                 5.14.0             pyhd8ed1ab_0    conda-forge
typing-extensions         4.8.0                    pypi_0    pypi
typing_extensions         4.9.0              pyha770c72_0    conda-forge
tzdata                    2023c                h04d1e81_0  
wcwidth                   0.2.12             pyhd8ed1ab_0    conda-forge
wheel                     0.41.2          py311hecd8cb5_0  
xz                        5.4.5                h6c40b1e_0  
zeromq                    4.3.4                he49afe7_1    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h4dc903c_0  